#+TITLE: Assignment 3 - Program Verification Using Dafny

** Task 1
Define the insertion sort algorithm as a transition system.
*** Transition System Definition
$S_{insertionSort} = <X,X^{o},U,\rightarrow,Y,h>$

1. We define the state space of the system as $X =$
   array\<nat\> $\times \mathbb{N} $\times \mathbb{N}$
2. We define an initialization function $\rho: array<nat>
   \rightarrow X$, which converts the input space
   to state space.
3. $\rho(a) = X^o = (a, 0, a.Length)$ where $a \in array<nat>$
4. U = {next}
5. Transition relation $(a,i,n) \xrightarrow[]{next} (a',i + 1,n) if \forall x\in
   [0, \alpha - 1], a'[x] = a[x]$ and $\forall x\in [\alpha + 1, i], a'[x + 1] =
   a[x]$ where $\alpha = min\{k|(0 \le k < i) \land a[k] < a[i] \}$ and i < n;
   else no transition i.e. terminal state.
6. Y = array\<nat\>
7. $h:X \rightarrow Y$
8. $h(x) = x[0]$, where $x \in X$ and $x[0]$ is
   the 1^{st} element from the 2 tuple state
   vector.
** Task 2
Program the insertion sort algorithm in Dafny.
*** Insertion Sort Program
 #+BEGIN_SRC :tangle
method insertionSort(a : array<nat>)
    modifies a
{
    var i := 0;
    while (i < a.Length)
    {
        var j := i - 1;
        while (j >= 0 && a[j] > a[j + 1])
        {
            a[j], a[j + 1] := a[j + 1], a[j];
            j := j - 1;
        }
        i := i + 1;
    }
}

// Input Space
datatype InputSpace = InputSpace(a:array<nat>)

// State Space
datatype StateSpace = StateSpace(a:array<nat>, idx:nat)

predicate sorted(state: StateSpace, begin: int, end: int)
    reads state.a
    requires state.a.Length > 0
{
    forall i, j :: 0 <= begin <= i <= j <= end < state.a.Length ==> state.a[i] <= state.a[j]
}

method insertionSortTransitionSystem(initialState : StateSpace) returns (terminalState:StateSpace)
    modifies initialState.a
    requires initialState.a.Length > 0
    ensures terminalState.a.Length > 0
    ensures multiset(initialState.a[..]) == multiset(terminalState.a[..])
    ensures sorted(terminalState, 0, terminalState.a.Length - 1)
{
    var i := 0;
    while (i < initialState.a.Length)
        decreases initialState.a.Length - i
        invariant 0 <= i <= initialState.a.Length
        invariant sorted(initialState, 0, i - 1)
    {
        var j := i - 1;
        while (j >= 0 && initialState.a[j] > initialState.a[j + 1])
            invariant -1 <= j <= i - 1
            invariant forall k :: j + 1 < k <= i ==> initialState.a[j + 1] < initialState.a[k]
            invariant forall m, n :: 0 <= m <= j && j + 2 <= n <= i ==> initialState.a[m] <= initialState.a[n]
            invariant sorted(initialState, 0, j)
            invariant sorted(initialState, j + 2, i)
            decreases j
        {
            initialState.a[j], initialState.a[j + 1] := initialState.a[j + 1], initialState.a[j];
            j := j - 1;
        }
        i := i + 1;
    }
    assert sorted(initialState, 0, initialState.a.Length - 1);
    terminalState := initialState;
}

// Orchestrator
method Main()
{
    var arr := new nat[10];
    arr[0] := 9;
    arr[1] := 8;
    arr[2] := 7;
    arr[3] := 6;
    arr[4] := 5;
    arr[5] := 4;
    arr[6] := 3;
    arr[7] := 2;
    arr[8] := 1;
    arr[9] := 0;
    var inputParameters := InputSpace(arr);
    var initialState := StateSpace(arr, 4);
    var terminalState := insertionSortTransitionSystem(initialState);
    var output := terminalState.a;
    assert sorted(StateSpace(output, output.Length - 1), 0, output.Length - 1);
    insertionSort(arr);
    var x := 0;
    while(x < output.Length)
    {
        print(output[x]);
        x := x + 1;
    }
    print("\n");
    x := 0;
    while(x < arr.Length)
    {
        print(arr[x]);
        x := x + 1;
    }
}
 #+END_SRC

** Task 3
In your Dafny program, clearly illustrate the Hoare Logic Predicates that
together demonstrate the partial and total correctness of your program, in-
cluding any loop invariants. Compile the program with 0 errors to verify.
You will be evaluated on the sufficiency and correctness of the program
and the predicates implemented in the Dafny program.

The preconditions in the Hoare triple are:
#+BEGIN_SRC
modifies initialState.a
requires initialState.a.Length > 0
#+END_SRC
and the postconditions in the Hoare triple are:
#+BEGIN_SRC
ensures terminalState.a.Length > 0
ensures multiset(initialState.a[..]) == multiset(terminalState.a[..])
ensures sorted(terminalState, 0, terminalState.a.Length - 1)
#+END_SRC
For the outer loop, the invariant
#+BEGIN_SRC
invariant sorted(initialState, 0, i - 1)
#+END_SRC
is sufficient for partial correctness, and the invariant
#+BEGIN_SRC
decreases initialState.a.Length - i
#+END_SRC
is sufficient to prove total correctness.

For the inner loop, the invarints
#+BEGIN_SRC
invariant forall k :: j + 1 < k <= i ==> initialState.a[j + 1] < initialState.a[k]
invariant forall m, n :: 0 <= m <= j && j + 2 <= n <= i ==> initialState.a[m] <= initialState.a[n]
invariant sorted(initialState, 0, j)
invariant sorted(initialState, j + 2, i)
#+END_SRC
are sufficient for partial correctness, and the invariant
#+BEGIN_SRC
decreases j
#+END_SRC
is sufficient to prove total correctness.

Thus for outer loop, the Hoare logic is
\infer{\{P\}\textrm{ while $B$ do $S$ done }\{\neg B\land P\}}{\{P\land B\}S\{P\}}
where,
1. P = Logical and of preconditions
2. S = lines 43-47 from insertion.dfy
3. B = Condition on line 38

Similarly, for inner loop, the Hoare logic is
\infer{\{P\}\textrm{ while $B$ do $S$ done }\{\neg B\land P\}}{\{P\land B\}S\{P\}}
where,
1. P = Logical and of preconditions
2. S = lines 52-53 from insertion.dfy
3. B = Condition on line 44

This is sufficient for partial correctness.

Observe that for total correctness, the boolean predicates $B$ for both inner
and outer loop eventually become false as i and j keep incrementing and
decrementing respectively, thus eventually terminating the loop. Hence, total
correctness in ensured. The decreases statement on line 39 and line 50 reflect
this.
